# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

os:
  - linux

before_install:
  - if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install tcolorbox framed; fi
  - if [[ "$OSTYPE" == "linux-gnu" ]]; then tlmgr install tcolorbox; fi

cache: packages

r_packages:
  - covr


r_build_args: '--compact-vignettes="gs+qpdf"'

addons:
  apt:
    packages:
      - ghostscript

matrix:
  allow_failures:
    - r: devel

after_success:
  - Rscript -e 'library(covr); codecov()'
